### ISSUE TITLE
Dependency 'sortedcontainers', 'six' gets dropped in 1.7.6

### ISSUE THREAD

**Issue by xkortex** [dsoftwareinc/fakeredis-py#25]
**Describe the bug**
Suddenly started encountering `ModuleNotFoundError: No module named 'sortedcontainers'` on `import fakeredis` in previously stable builds. Also seems like `six` is missing (though that's almost always in the env)

```
  • Installing fakeredis (1.7.6)
  • Installing imageio (2.19.2)
  • Installing moto (3.1.10)
  • Installing opencv-python-headless (4.5.5.64)
  • Installing pydub (0.25.1)
  • Installing pytest-mock (3.7.0)

...

    @pytest.fixture()
    def fake_redis():
>       import fakeredis

tests/conftest.py:17: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fakeredis/__init__.py:1: in <module>
    from ._server import FakeServer, FakeRedis, FakeStrictRedis, FakeConnection   # noqa: F401
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fakeredis/_server.py:21: in <module>
    from ._zset import ZSet
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   import sortedcontainers
E   ModuleNotFoundError: No module named 'sortedcontainers'

/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fakeredis/_zset.py:1: ModuleNotFoundError
```

**To Reproduce**
1. Fresh environment (eg `docker run --rm -it python:3.8.10 bash`)
2. `pip install fakeredis==1.7.6`
3. `python -c "import fakeredis"`

Oops, looks like `six` is also missing: 
```
root@a6be9ecaf7f8:/# python -c "import fakeredis"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/fakeredis/__init__.py", line 1, in <module>
    from ._server import FakeServer, FakeRedis, FakeStrictRedis, FakeConnection   # noqa: F401
  File "/usr/local/lib/python3.8/site-packages/fakeredis/_server.py", line 19, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```
no prob, let's install that
```
root@a6be9ecaf7f8:/# pip install six
Collecting six
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: six
Successfully installed six-1.16.0

root@a6be9ecaf7f8:/# python -c "import fakeredis"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/fakeredis/__init__.py", line 1, in <module>
    from ._server import FakeServer, FakeRedis, FakeStrictRedis, FakeConnection   # noqa: F401
  File "/usr/local/lib/python3.8/site-packages/fakeredis/_server.py", line 21, in <module>
    from ._zset import ZSet
  File "/usr/local/lib/python3.8/site-packages/fakeredis/_zset.py", line 1, in <module>
    import sortedcontainers
ModuleNotFoundError: No module named 'sortedcontainers'
```
Resolved by installing sortedcontainers: 
```
root@a6be9ecaf7f8:/# pip install sortedcontainers
Collecting sortedcontainers
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Installing collected packages: sortedcontainers
Successfully installed sortedcontainers-2.4.0

root@a6be9ecaf7f8:/# python -c "import fakeredis"
```
**Expected behavior**
successful import

**Desktop (please complete the following information):**
 - OS: macOS
 - python version : 3.8
 - redis-py version

**Additional context**

**Comment by xkortex** [comment]
Oops, dupe of https://github.com/dsoftwareinc/fakeredis-py/issues/23

Weird, I definitely searched for 'sortedcontainers' in issues and nothing came up.
