### ISSUE TITLE
fakeredis does not work out-of-the-box with redis-py versions earlier than 4.1.0

### ISSUE THREAD

**Issue by Jamie-** [dsoftwareinc/fakeredis-py#34]
**Describe the bug**
fakeredis does not work out-of-the-box with redis-py versions earlier than 4.1.0 since https://github.com/dsoftwareinc/fakeredis-py/commit/62133d260e9a7362429060b787d37597006f5d20 as importlib-metadata was not a redis-py dependency before this point.

redis-py introduced importlib-metadata in 4.1.0. You can see this here https://github.com/redis/redis-py/compare/v4.0.2...v4.1.0 (click "Files changes" and scroll to `setup.py`)

**To Reproduce**
Using **Python 3.7**
```
pip install redis==3.5.3
pip install fakeredis
python -c "import fakeredis"
```

**Expected behavior**
fakeredis should require importlib-metadata itself as it is required as a direct dependency of the fakeredis code.

**Screenshots**
```
root@64fd5842abed:/# python -V
Python 3.7.13
root@64fd5842abed:/# pip install redis==3.5.3
Collecting redis==3.5.3
  Downloading redis-3.5.3-py2.py3-none-any.whl (72 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.1/72.1 KB 1.6 MB/s eta 0:00:00
Installing collected packages: redis
Successfully installed redis-3.5.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
root@64fd5842abed:/# pip install fakeredis
Collecting fakeredis
  Downloading fakeredis-1.8.1-py3-none-any.whl (35 kB)
Collecting sortedcontainers<3.0.0,>=2.4.0
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Requirement already satisfied: redis<4.4 in /usr/local/lib/python3.7/site-packages (from fakeredis) (3.5.3)
Collecting six<2.0.0,>=1.16.0
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: sortedcontainers, six, fakeredis
Successfully installed fakeredis-1.8.1 six-1.16.0 sortedcontainers-2.4.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
root@64fd5842abed:/# python -c "import fakeredis"
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/fakeredis/__init__.py", line 4, in <module>
    from importlib import metadata
ImportError: cannot import name 'metadata' from 'importlib' (/usr/local/lib/python3.7/importlib/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/fakeredis/__init__.py", line 6, in <module>
    import importlib_metadata as metadata
ModuleNotFoundError: No module named 'importlib_metadata'
root@64fd5842abed:/# 
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Python 3.7.13
 - redis-py 3.5.3

**Comment by cunla** [comment]
Hi, I am not able to reproduce this.
I created the following `docker-compose.yaml` and the error described does not happen.
```
version: '3.8'

services:
  test3.7-old:
    image: python:3.7
    volumes:
      - ./fakeredis/:/src/fakeredis/
      - ./test/:/src/test/
      - ./pyproject.toml:/src/pyproject.toml
      - ./poetry.lock:/src/poetry.lock
      - ./README.md:/src/README.md
    environment:
      REDIS_URL: "redis://user:password@host:11234"
    command:
      - /bin/bash
      - -c
      - |
        pip install fakeredis
        pip install redis==3.5.3
        python -c "import fakeredis"
```

**Comment by Jamie-** [comment]
I'm just as perplexed now, I was able to repro this reliably in my CI for a few days in a row and then suddenly it's gone and I can't repro it any more :thinking:
